import type { Lesson } from "../lessons/catalog";
import type { LessonPracticeExercise } from "../lessons/catalog";
import { getLearningItemId, type LearningItem, type LessonProgress, type LessonProgressStage } from "../vocabulary/learning-record";

export type LessonStage = "read" | "notice" | "practise" | "replay" | "keep";
export type LessonPracticeEvidence = { candidateId: string; dimension: "recognition" | "recall"; result: "again" | "got-it" };
export type LessonTransferResult = "correct" | "incorrect";
export type LessonAuthoredExerciseResult = "correct" | "incorrect";
export type LessonSession = { lesson: Lesson; stage: LessonStage; revealedLineIndexes: number[]; selectedCandidateIds: string[]; practiceIndex: number; practiceRevealed: boolean; practiceEvidence: LessonPracticeEvidence[]; transferAnswer: string | null; transferChecked: boolean; transferResult: LessonTransferResult | null; transferRecorded: boolean; authoredExerciseIndex: number; authoredAnswer: string | null; authoredTokens: string[]; authoredChecked: boolean; authoredResult: LessonAuthoredExerciseResult | null; authoredRecorded: boolean };
export type LessonFilterStatus = "all" | "ready" | "continue" | "completed";
export type LessonFilterLevel = Lesson["cefr"] | "all";
export type LessonAvailability = LessonFilterStatus | "completed";
const stages: LessonStage[] = ["read", "notice", "practise", "replay", "keep"];

export function createLessonSession(lesson: Lesson, stage: LessonProgressStage = "read"): LessonSession { return { lesson, stage, revealedLineIndexes: [], selectedCandidateIds: lesson.candidates.map((candidate) => candidate.id), practiceIndex: 0, practiceRevealed: false, practiceEvidence: [], transferAnswer: null, transferChecked: false, transferResult: null, transferRecorded: false, authoredExerciseIndex: 0, authoredAnswer: null, authoredTokens: [], authoredChecked: false, authoredResult: null, authoredRecorded: false }; }
export function resumeLessonSession(lesson: Lesson, progress: LessonProgress | null): LessonSession { const stage = progress && progress.completedAt !== null ? "read" : progress?.stage; return createLessonSession(lesson, stage === "replay" ? "practise" : stage); }
export function getLessonCandidateChoices(session: LessonSession, items: LearningItem[]): Array<{ id: string; dutch: string; checked: boolean; alreadySaved: boolean }> { return session.lesson.candidates.map((candidate) => ({ id: candidate.id, dutch: candidate.dutch, checked: session.selectedCandidateIds.includes(candidate.id), alreadySaved: items.some((item) => item.id === getLearningItemId(candidate.dutch)) })); }
export function getLessonsAvailabilityView(error: string | null): { unavailable: boolean; message: string | null; retryLabel: string | null } { return error ? { unavailable: true, message: error, retryLabel: "Try lessons again" } : { unavailable: false, message: null, retryLabel: null }; }
export function getLessonAvailability(progress: LessonProgress | null | undefined): LessonAvailability { return !progress ? "ready" : progress.completedAt === null ? "continue" : "completed"; }
export function filterLessons(lessons: Lesson[], progressById: Record<string, LessonProgress | null>, status: LessonFilterStatus, level: LessonFilterLevel): Lesson[] { return lessons.filter((lesson) => (level === "all" || lesson.cefr === level) && (status === "all" || getLessonAvailability(progressById[lesson.id]) === status)); }
export function advanceLessonStage(session: LessonSession): LessonSession { const index = stages.indexOf(session.stage); return { ...session, stage: stages[Math.min(index + 1, stages.length - 1)], practiceRevealed: false }; }
export function revealLessonLine(session: LessonSession, index: number): LessonSession { return session.revealedLineIndexes.includes(index) ? session : { ...session, revealedLineIndexes: [...session.revealedLineIndexes, index] }; }
export function toggleLessonCandidate(session: LessonSession, id: string): LessonSession { return { ...session, selectedCandidateIds: session.selectedCandidateIds.includes(id) ? session.selectedCandidateIds.filter((candidateId) => candidateId !== id) : [...session.selectedCandidateIds, id] }; }
export function revealLessonPractice(session: LessonSession): LessonSession { return { ...session, practiceRevealed: true }; }
export function advanceLessonPractice(session: LessonSession, result: "again" | "got-it"): LessonSession { const prompt = session.lesson.practice[session.practiceIndex]; const practiceEvidence = [...session.practiceEvidence, { candidateId: prompt.candidateId, dimension: prompt.dimension, result }]; return session.practiceIndex + 1 >= session.lesson.practice.length ? { ...session, stage: "practise", practiceIndex: session.lesson.practice.length, practiceRevealed: false, practiceEvidence, authoredExerciseIndex: 0, authoredAnswer: null, authoredTokens: [], authoredChecked: false, authoredResult: null, authoredRecorded: false } : { ...session, practiceIndex: session.practiceIndex + 1, practiceRevealed: false, practiceEvidence }; }
export function selectLessonTransferAnswer(session: LessonSession, answer: string): LessonSession { const transfer = session.lesson.practiceEnvelope?.transfer; return !transfer || session.transferChecked || !transfer.choices.includes(answer) ? session : { ...session, transferAnswer: answer }; }
export function checkLessonTransfer(session: LessonSession): LessonSession { const transfer = session.lesson.practiceEnvelope?.transfer; if (!transfer || session.transferAnswer === null || session.transferChecked) return session; const correct = transfer.accepted.includes(session.transferAnswer); const evidence = session.transferRecorded ? session.practiceEvidence : [...session.practiceEvidence, { candidateId: transfer.candidateId, dimension: "recognition" as const, result: correct ? "got-it" as const : "again" as const }]; return { ...session, transferChecked: true, transferResult: correct ? "correct" : "incorrect", practiceEvidence: evidence, transferRecorded: true }; }
export function resetLessonTransfer(session: LessonSession): LessonSession { return { ...session, transferAnswer: null, transferChecked: false, transferResult: null }; }
export function advanceLessonTransfer(session: LessonSession): LessonSession { return !session.lesson.practiceEnvelope || session.transferResult !== "correct" ? session : { ...advanceLessonStage(session), transferAnswer: null, transferChecked: false, transferResult: null }; }
export function getLessonPracticeExercises(session: LessonSession): LessonPracticeExercise[] { return session.lesson.practicalDutch ? session.lesson.practicalDutch.coreExercises.map((exercise, index) => ({ contentVersion: 1, id: exercise.id, primitive: exercise.kind === "order" ? "order-tokens" : index === 0 ? "contrast-form" : "repair-choice", candidateId: session.lesson.candidates[index % session.lesson.candidates.length]?.id ?? "", dimension: index === 0 ? "recognition" : "recall", prompt: exercise.prompt.en, context: exercise.context.nl, choices: exercise.choices, ...(exercise.tokens ? { tokens: exercise.tokens } : {}), accepted: exercise.accepted, distractors: exercise.distractors, feedback: exercise.feedback.en, review: { author: exercise.review.author, reviewState: "second-review-complete", reviewer: exercise.review.reviewer, reviewedAt: exercise.review.reviewedAt, sources: exercise.review.sources, provenance: exercise.review.provenance } })) : session.lesson.practiceExercises; }
export function selectLessonPracticeExerciseAnswer(session: LessonSession, answer: string): LessonSession { const exercise = getLessonPracticeExercises(session)[session.authoredExerciseIndex]; return !exercise || session.authoredChecked || !exercise.choices.includes(answer) ? session : { ...session, authoredAnswer: answer }; }
export function toggleLessonPracticeExerciseToken(session: LessonSession, token: string): LessonSession { const exercise = getLessonPracticeExercises(session)[session.authoredExerciseIndex]; if (!exercise || exercise.primitive !== "order-tokens" || session.authoredChecked || !exercise.tokens?.includes(token)) return session; const tokens = session.authoredTokens.includes(token) ? session.authoredTokens.filter((candidate) => candidate !== token) : [...session.authoredTokens, token]; return { ...session, authoredTokens: tokens, authoredAnswer: tokens.length > 0 ? tokens.join(" ") : null }; }
export function checkLessonPracticeExercise(session: LessonSession): LessonSession { const exercise = getLessonPracticeExercises(session)[session.authoredExerciseIndex]; const answer = exercise?.primitive === "order-tokens" ? session.authoredTokens.join(" ") : session.authoredAnswer; if (!exercise || !answer || session.authoredChecked) return session; const correct = exercise.accepted.includes(answer); const evidence = session.authoredRecorded ? session.practiceEvidence : [...session.practiceEvidence, { candidateId: exercise.candidateId, dimension: exercise.dimension, result: correct ? "got-it" as const : "again" as const }]; return { ...session, authoredAnswer: answer, authoredChecked: true, authoredResult: correct ? "correct" : "incorrect", authoredRecorded: true, practiceEvidence: evidence }; }
export function advanceLessonPracticeExercise(session: LessonSession): LessonSession { const exercises = getLessonPracticeExercises(session); if (session.authoredResult !== "correct") return session; if (session.authoredExerciseIndex + 1 >= exercises.length) return { ...advanceLessonStage(session), authoredExerciseIndex: exercises.length, authoredAnswer: null, authoredTokens: [], authoredChecked: false, authoredResult: null, authoredRecorded: false }; return { ...session, authoredExerciseIndex: session.authoredExerciseIndex + 1, authoredAnswer: null, authoredTokens: [], authoredChecked: false, authoredResult: null, authoredRecorded: false }; }
