import { readFileSync } from "node:fs";
import path from "node:path";

import { describe, expect, it } from "vitest";

const styles = readFileSync(path.join(import.meta.dirname, "styles.css"), "utf8");

describe("popup layout", () => {
  it("uses the actual remaining popup height for scrollable content", () => {
    expect(styles).toContain(".popup-shell { display: flex; flex-direction: column;");
    expect(styles).toContain(".popup-content { display: grid; flex: 1 1 auto; min-height: 0;");
    expect(styles).toContain("overflow-x: hidden");
    expect(styles).toContain(".button { min-height: 48px;");
    expect(styles).toContain(".lesson-filter { min-height: 44px;");
    expect(styles).toContain("@media (prefers-reduced-motion: reduce)");
    expect(styles).toContain(".rhythm-day { min-height: 44px;");
    expect(styles).toContain(".lesson-row { display: grid; grid-template-columns: 30px minmax(0, 1fr) auto;");
    expect(styles).toContain("padding: 6px 8px;");
    expect(styles).toContain(".saved-row { display: grid; grid-template-columns: 30px minmax(0, 1fr) auto; gap: 9px; width: 100%; min-width: 0; min-height: 70px; padding: 10px 8px;");
    expect(styles).toContain("transform: translateX(2px)");
    expect(styles).toContain("transition-duration: 0.01ms !important");
    expect(styles).toContain(".month-weekdays { display: grid; grid-template-columns: repeat(7, 1fr);");
    expect(styles).toContain(".heatmap-month .rhythm-day { position: relative; display: grid; min-height: 36px; aspect-ratio: auto; place-items: center;");
    expect(styles).not.toContain(".heatmap .rhythm-day.high { background: var(--black); }");
    expect(styles).toContain(".activity-total { font-family: var(--serif);");
    expect(styles).toContain(".popup-content.today-panel { display: flex; align-items: stretch; overflow-y: auto; padding: 12px; }");
    expect(styles).toContain(".popup-content.lesson-panel { padding: 0; }");
    expect(styles).toContain(".brief-today.today-week { display: flex; flex: 1 1 auto; flex-direction: column; justify-content: space-between; min-height: 100%; }");
    expect(styles).toContain(".calendar-focus { display: flex; flex: 0 0 100%; flex-direction: column; justify-content: space-between; width: 100%; min-height: 100%; }");
    expect(styles).toContain(".today-week .learning-rhythm { min-width: 0; }");
    expect(styles).toContain(".completion-copy { white-space: normal; font-size: .64rem; letter-spacing: -.01em; }");
    expect(styles).toContain(".rhythm-day.is-today { box-shadow: inset 0 0 0 2px var(--black); }");
    expect(styles).toContain(".heatmap-month { width: 100%; grid-auto-rows: 36px; }");
    expect(styles).toContain(".next-action .lesson-entry-button { width: min(100%, 220px); justify-self: center; background: var(--white) !important; }");
    expect(styles).toContain(".review-completion-meta { margin: -2px 0 0; color: var(--muted);");
    expect(styles).toContain(".lesson-completion-meta { margin: -2px 0 0; color: var(--muted);");
    expect(styles).toContain(".grammar-capability { margin: -4px 0 0; color: var(--muted);");
    expect(styles).toContain(".grammar-choices { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 8px; }");
    expect(styles).toContain(".grammar-choices .is-selected { background: var(--black); color: var(--white); }");
    expect(styles).toContain(".contrast-repair-offer { display: grid;");
    expect(styles).toContain(".contrast-offer-copy { margin: 0;");
    expect(styles).toContain(".button { min-height: 48px; padding: 8px 10px; border: 1px solid var(--black); border-radius: 8px; background: var(--white); color: var(--black); font-size: .875rem;");
    expect(styles).toContain(".lesson-filters { display: grid; gap: 5px;");
    expect(styles).toContain(".lesson-filter { min-height: 44px;");
    expect(styles).toContain(".tabs.is-locked");
    expect(styles).toContain(".tab:not(.is-active):not(:disabled):hover");
    expect(styles).toContain(".saved-quiz-entry");
    expect(styles).toContain(".saved-quiz-error");
    expect(styles).toContain(".lesson-category-groups { display: grid;");
    expect(styles).toContain(".verb-notice-highlight");
    expect(styles).toContain(".verb-map-label-sub");
    expect(styles).toContain(".verb-form-status");
    expect(styles).not.toContain("var(--dm-success)");
    expect(styles).toContain(".verb-form-card.selected { border-color: var(--dm-ink-strong);");
    expect(styles).toContain(".due-badge[hidden] { display: none; }");
    expect(styles).toContain(".practice-card { display: grid; gap: 12px; min-width: 0;");
    expect(styles).toContain(".practice-card .heading { min-width: 0; overflow-wrap: anywhere;");
    expect(styles).toContain(".meaning-row span { min-width: 0; overflow-wrap: anywhere;");
    expect(styles).toContain(".lesson-content .practice-card .heading,\n.lesson-content .lesson-transfer .heading { font-size: var(--dm-font-size-h2); line-height: var(--dm-line-height-h2); }");
    expect(styles).toContain(".lesson-content .lesson-transfer { display: grid; gap: 8px; }");
    expect(styles).toContain(".lesson-content .practice-card .button,\n.lesson-content .lesson-transfer .button { min-height: var(--dm-target-min);");
    expect(styles).toContain(".lesson-content .practice-card .grammar-feedback,\n.lesson-content .lesson-transfer .grammar-feedback { margin: 0; font-size: var(--dm-font-size-small);");
    expect(styles).toContain(".lesson-content.focused-content { gap: 0; padding: 2px 16px 16px; }");
    expect(styles).toContain(".lesson-content.focused-content > .exit-button { justify-self: center;");
    expect(styles).toContain(".lesson-content .lesson-rail { gap: 0; margin-bottom: 12px; }");
    expect(styles).toContain(".lesson-content .lesson-stage { display: grid; min-height: var(--dm-target-min); place-items: center;");
    expect(styles).toContain(".lesson-content .story-line .helper-copy { margin: 0; color: var(--dm-ink-muted); font-size: var(--dm-font-size-small); line-height: var(--dm-line-height-small); }");
    expect(styles).toContain(".year-month-labels span { min-width: 0; white-space: nowrap; }");
  });
});
