import type { DutchTense, EnglishComparisonVariant, EnglishMapRecord, EnglishTense, JourneyRecord, VerbJourneyPack } from "./content";

type LocalizedComparison = Omit<EnglishComparisonVariant, "en">;
type ComparisonContent = {
  meaningPreserving: LocalizedComparison;
  everyday: LocalizedComparison;
  cue: { display: string; shortMeaning: string; kind: "frequency" | "current-time" | "current-period" | "duration" | "past-time" | "past-reference" | "sequence" | "future-time" | "deadline" | "compound"; tokens: string[] };
  howDutchExpressesIt: string;
  whyTheyDiffer: string;
};

const localized = (nl: string, te: string, form: DutchTense): LocalizedComparison => ({ nl, te, form });

const englishComparisonBase: EnglishMapRecord[] = [
  { id: "english.gaan.present-simple", englishTense: "present-simple", group: "present", english: "I go to work by train every day.", situation: "A repeated movement routine.", meaningPreservingDutch: "Ik ga elke dag met de trein naar mijn werk.", commonEverydayDutch: "Ik ga elke dag met de trein naar mijn werk.", dutchAnalysis: { primaryForm: "OTT" }, mismatchNote: "Dutch uses OTT for a repeated movement routine.", cefrLevel: "A1", teachingPriority: "core" },
  { id: "english.gaan.present-continuous", englishTense: "present-continuous", group: "present", english: "I am going home now.", situation: "Movement happening now.", meaningPreservingDutch: "Ik ben nu op weg naar huis.", commonEverydayDutch: "Ik ga nu naar huis.", dutchAnalysis: { primaryForm: "OTT", construction: "OTT + nu" }, mismatchNote: "Dutch often uses ordinary OTT with nu; it does not need a separate continuous tense.", cefrLevel: "A1", teachingPriority: "core" },
  { id: "english.gaan.present-perfect", englishTense: "present-perfect", group: "present", english: "I have gone to the shop.", situation: "Completed movement connected to now.", meaningPreservingDutch: "Ik ben naar de winkel gegaan.", commonEverydayDutch: "Ik ben naar de winkel gegaan.", dutchAnalysis: { primaryForm: "VTT" }, mismatchNote: "This authored movement example uses zijn plus gegaan in VTT.", cefrLevel: "A2", teachingPriority: "core" },
  { id: "english.gaan.present-perfect-continuous", englishTense: "present-perfect-continuous", group: "present", english: "I have been going there every week.", situation: "A repeated movement continuing through the current period.", meaningPreservingDutch: "Ik ga daar elke week heen.", commonEverydayDutch: "Ik ga daar elke week heen.", dutchAnalysis: { primaryForm: "OTT", construction: "OTT + frequency" }, mismatchNote: "Dutch uses OTT and a frequency cue rather than a separate perfect-continuous form.", cefrLevel: "A2", teachingPriority: "later" },
  { id: "english.gaan.past-simple", englishTense: "past-simple", group: "past", english: "I went home yesterday.", situation: "A completed movement in a past conversation.", meaningPreservingDutch: "Ik ging gisteren naar huis.", commonEverydayDutch: "Ik ben gisteren naar huis gegaan.", dutchAnalysis: { primaryForm: "VTT", alternativeForms: ["OVT"] }, mismatchNote: "A standalone completed event often uses VTT in everyday Dutch; OVT can frame the past movement as background.", cefrLevel: "A2", teachingPriority: "core" },
  { id: "english.gaan.past-continuous", englishTense: "past-continuous", group: "past", english: "I was going to work when it started raining.", situation: "Movement in progress around another past event.", meaningPreservingDutch: "Ik ging naar mijn werk toen het begon te regenen.", commonEverydayDutch: "Ik ging naar mijn werk toen het begon te regenen.", dutchAnalysis: { primaryForm: "OVT" }, mismatchNote: "Dutch uses OVT and the surrounding context for this ongoing past movement.", cefrLevel: "A2", teachingPriority: "core" },
  { id: "english.gaan.past-perfect", englishTense: "past-perfect", group: "past", english: "I had gone home before the rain started.", situation: "Movement completed before another past reference point.", meaningPreservingDutch: "Ik was naar huis gegaan voordat het regende.", commonEverydayDutch: "Ik was naar huis gegaan voordat het regende.", dutchAnalysis: { primaryForm: "VVT" }, mismatchNote: "VVT places the completed movement before the past reference point.", cefrLevel: "A2", teachingPriority: "later" },
  { id: "english.gaan.past-perfect-continuous", englishTense: "past-perfect-continuous", group: "past", english: "I had been going there for weeks.", situation: "Repeated movement measured up to a past point.", meaningPreservingDutch: "Ik ging daar al weken heen.", commonEverydayDutch: "Ik ging daar al weken heen.", dutchAnalysis: { primaryForm: "OVT", construction: "OVT + al + duration" }, mismatchNote: "Dutch commonly uses OVT with a duration phrase instead of a separate past-perfect-continuous form.", cefrLevel: "reference", teachingPriority: "reference" },
  { id: "english.gaan.future-simple", englishTense: "future-simple", group: "future", english: "I will go tomorrow.", situation: "An explicit future movement.", meaningPreservingDutch: "Ik zal morgen gaan.", commonEverydayDutch: "Morgen ga ik.", dutchAnalysis: { primaryForm: "OTT", construction: "future time + OTT", alternativeForms: ["OTTT"] }, mismatchNote: "Dutch often uses OTT with a future time cue; zal gaan makes the future explicit.", cefrLevel: "A1", teachingPriority: "core" },
  { id: "english.gaan.future-continuous", englishTense: "future-continuous", group: "future", english: "Tomorrow at eight, I will be going to work.", situation: "Movement at a future time.", meaningPreservingDutch: "Morgen om acht uur ga ik naar mijn werk.", commonEverydayDutch: "Morgen om acht uur ga ik naar mijn werk.", dutchAnalysis: { primaryForm: "OTT", construction: "future time + OTT" }, mismatchNote: "The future time phrase carries the future meaning; Dutch does not need a separate future-continuous form.", cefrLevel: "A2", teachingPriority: "later" },
  { id: "english.gaan.future-perfect", englishTense: "future-perfect", group: "future", english: "By Friday, I will have gone home.", situation: "Movement completed before a future deadline.", meaningPreservingDutch: "Tegen vrijdag zal ik naar huis gegaan zijn.", commonEverydayDutch: "Tegen vrijdag ben ik naar huis gegaan.", dutchAnalysis: { primaryForm: "VTTT", alternativeForms: ["VTT"] }, mismatchNote: "VTTT marks completion before a future point explicitly; everyday Dutch may use VTT with the deadline.", cefrLevel: "reference", teachingPriority: "reference" },
  { id: "english.gaan.future-perfect-continuous", englishTense: "future-perfect-continuous", group: "future", english: "By June, I will have been going there for a year.", situation: "Repeated movement continuing up to a future point.", meaningPreservingDutch: "In juni ga ik daar al een jaar heen.", commonEverydayDutch: "In juni ga ik daar al een jaar heen.", dutchAnalysis: { primaryForm: "OTT", construction: "future time + OTT + duration", alternativeForms: ["VTTT"] }, mismatchNote: "Dutch normally uses OTT, a future cue, and duration rather than a separate future-perfect-continuous form.", cefrLevel: "reference", teachingPriority: "reference" },
];

const comparisonContent: Record<EnglishTense, ComparisonContent> = {
  "present-simple": { meaningPreserving: localized("Ik ga elke dag met de trein naar mijn werk.", "నేను ప్రతి రోజు రైలులో పనికి వెళ్తాను.", "OTT"), everyday: localized("Ik ga elke dag met de trein naar mijn werk.", "నేను ప్రతి రోజు రైలులో పనికి వెళ్తాను.", "OTT"), cue: { display: "elke dag", shortMeaning: "repeated routine", kind: "frequency", tokens: ["elke dag"] }, howDutchExpressesIt: "Both roles use OTT gaan with a frequency cue.", whyTheyDiffer: "Dutch uses the present form ga for a repeated movement routine." },
  "present-continuous": { meaningPreserving: localized("Ik ben nu op weg naar huis.", "నేను ఇప్పుడు ఇంటికి వెళ్తున్నాను.", "OTT"), everyday: localized("Ik ga nu naar huis.", "నేను ఇప్పుడు ఇంటికి వెళ్తున్నాను.", "OTT"), cue: { display: "nu", shortMeaning: "movement now", kind: "current-time", tokens: ["nu"] }, howDutchExpressesIt: "Meaning-preserving: op weg naar huis. Everyday: OTT ga + nu.", whyTheyDiffer: "Dutch often uses ordinary OTT when nu already makes the current movement clear." },
  "present-perfect": { meaningPreserving: localized("Ik ben naar de winkel gegaan.", "నేను దుకాణానికి వెళ్లాను.", "VTT"), everyday: localized("Ik ben naar de winkel gegaan.", "నేను దుకాణానికి వెళ్లాను.", "VTT"), cue: { display: "naar de winkel", shortMeaning: "completed destination", kind: "current-period", tokens: ["naar de winkel"] }, howDutchExpressesIt: "Both roles use VTT ben gegaan for completed movement.", whyTheyDiffer: "This authored movement example uses zijn plus gegaan, not hebben." },
  "present-perfect-continuous": { meaningPreserving: localized("Ik ga daar elke week heen.", "నేను ప్రతి వారం అక్కడికి వెళ్తాను.", "OTT"), everyday: localized("Ik ga daar elke week heen.", "నేను ప్రతి వారం అక్కడికి వెళ్తాను.", "OTT"), cue: { display: "elke week", shortMeaning: "repeated movement", kind: "frequency", tokens: ["elke week"] }, howDutchExpressesIt: "Both roles use OTT gaan with a repeated-time cue.", whyTheyDiffer: "Dutch uses a present routine rather than a separate present-perfect-continuous tense." },
  "past-simple": { meaningPreserving: localized("Ik ging gisteren naar huis.", "నేను నిన్న ఇంటికి వెళ్లాను.", "OVT"), everyday: localized("Ik ben gisteren naar huis gegaan.", "నేను నిన్న ఇంటికి వెళ్లాను.", "VTT"), cue: { display: "gisteren", shortMeaning: "past movement", kind: "past-time", tokens: ["gisteren"] }, howDutchExpressesIt: "Meaning-preserving: OVT ging. Everyday: VTT ben gegaan for one completed conversational fact.", whyTheyDiffer: "English simple past can map to Dutch OVT or VTT depending on whether the speaker frames background or a completed event." },
  "past-continuous": { meaningPreserving: localized("Ik ging naar mijn werk toen het begon te regenen.", "వర్షం మొదలైనప్పుడు నేను పనికి వెళ్తున్నాను.", "OVT"), everyday: localized("Ik ging naar mijn werk toen het begon te regenen.", "వర్షం మొదలైనప్పుడు నేను పనికి వెళ్తున్నాను.", "OVT"), cue: { display: "toen", shortMeaning: "past situation around another event", kind: "past-reference", tokens: ["toen"] }, howDutchExpressesIt: "Both roles use OVT ging with the surrounding past clause.", whyTheyDiffer: "Dutch uses context and OVT rather than a separate past-continuous tense." },
  "past-perfect": { meaningPreserving: localized("Ik was naar huis gegaan voordat het regende.", "వర్షం పడకముందే నేను ఇంటికి వెళ్లిపోయాను.", "VVT"), everyday: localized("Ik was naar huis gegaan voordat het regende.", "వర్షం పడకముందే నేను ఇంటికి వెళ్లిపోయాను.", "VVT"), cue: { display: "voordat", shortMeaning: "earlier past sequence", kind: "sequence", tokens: ["voordat"] }, howDutchExpressesIt: "Both roles use VVT was gegaan before the past reference point.", whyTheyDiffer: "Was gegaan places the movement earlier than another past event." },
  "past-perfect-continuous": { meaningPreserving: localized("Ik ging daar al weken heen.", "నేను ఇప్పటికే వారాలుగా అక్కడికి వెళ్తున్నాను.", "OVT"), everyday: localized("Ik ging daar al weken heen.", "నేను ఇప్పటికే వారాలుగా అక్కడికి వెళ్తున్నాను.", "OVT"), cue: { display: "al weken", shortMeaning: "duration up to a past point", kind: "duration", tokens: ["al weken"] }, howDutchExpressesIt: "Both roles use OVT ging with al and a duration.", whyTheyDiffer: "Dutch normally uses OVT plus duration instead of a separate past-perfect-continuous form." },
  "future-simple": { meaningPreserving: localized("Ik zal morgen gaan.", "నేను రేపు వెళ్తాను.", "OTTT"), everyday: localized("Morgen ga ik.", "రేపు నేను వెళ్తాను.", "OTT"), cue: { display: "morgen", shortMeaning: "future movement", kind: "future-time", tokens: ["morgen"] }, howDutchExpressesIt: "Meaning-preserving: OTTT zal gaan. Everyday: OTT ga + morgen.", whyTheyDiffer: "Dutch often uses OTT with a future-time cue; zal gaan makes the future explicit." },
  "future-continuous": { meaningPreserving: localized("Morgen om acht uur ga ik naar mijn werk.", "రేపు ఎనిమిది గంటలకు నేను పనికి వెళ్తాను.", "OTT"), everyday: localized("Morgen om acht uur ga ik naar mijn werk.", "రేపు ఎనిమిది గంటలకు నేను పనికి వెళ్తాను.", "OTT"), cue: { display: "morgen om acht uur", shortMeaning: "movement at a future time", kind: "future-time", tokens: ["Morgen", "om acht uur"] }, howDutchExpressesIt: "Both roles use OTT ga with a future-time cue.", whyTheyDiffer: "The future time phrase supplies the future reference without a separate continuous form." },
  "future-perfect": { meaningPreserving: localized("Tegen vrijdag zal ik naar huis gegaan zijn.", "శుక్రవారం నాటికి నేను ఇంటికి వెళ్లి ఉంటాను.", "VTTT"), everyday: localized("Tegen vrijdag ben ik naar huis gegaan.", "శుక్రవారం నాటికి నేను ఇంటికి వెళ్లాను.", "VTT"), cue: { display: "tegen vrijdag", shortMeaning: "completion by a deadline", kind: "deadline", tokens: ["Tegen vrijdag"] }, howDutchExpressesIt: "Meaning-preserving: VTTT zal gegaan zijn. Everyday: VTT ben gegaan with the deadline.", whyTheyDiffer: "VTTT makes the future completion explicit; everyday Dutch may let the deadline carry that meaning." },
  "future-perfect-continuous": { meaningPreserving: localized("In juni ga ik daar al een jaar heen.", "జూన్‌లో నేను అక్కడికి వెళ్లి ఒక సంవత్సరం అవుతుంది.", "OTT"), everyday: localized("In juni ga ik daar al een jaar heen.", "జూన్‌లో నేను అక్కడికి వెళ్లి ఒక సంవత్సరం అవుతుంది.", "OTT"), cue: { display: "in juni + al een jaar", shortMeaning: "duration at a future point", kind: "compound", tokens: ["In juni", "al een jaar"] }, howDutchExpressesIt: "Both roles use OTT ga heen with a future cue and duration.", whyTheyDiffer: "Dutch normally uses a future-time phrase and duration rather than a separate future-perfect-continuous form." },
};

const englishComparison = englishComparisonBase.map((record) => ({
  ...record,
  meaningPreserving: { ...comparisonContent[record.englishTense].meaningPreserving, en: record.english },
  everyday: { ...comparisonContent[record.englishTense].everyday, en: record.english },
  cue: comparisonContent[record.englishTense].cue,
  howDutchExpressesIt: comparisonContent[record.englishTense].howDutchExpressesIt,
  whyTheyDiffer: comparisonContent[record.englishTense].whyTheyDiffer,
}));

const gaanForms = [
  { id: "form.gaan.ott", dutchTense: "OTT" as const, viewpoint: "present" as const, completion: "onvoltooid" as const, fullNameNl: "onvoltooid tegenwoordige tijd", sentence: "Ik ga vandaag naar de markt.", naturalEnglish: "I am going to the market today.", usageMeaning: "movement, departure, or a current plan", formula: "ik ga · jij gaat · hij/zij gaat · wij gaan", commonUsage: "Ik ga naar huis. / Ga je mee?", learnerLabelEn: "Present movement or plan", canonicalExample: { nl: "Ik ga vandaag naar de markt.", en: "I am going to the market today.", te: "నేను ఈ రోజు మార్కెట్‌కు వెళ్తాను." }, commonUsageExample: { nl: "Ga je mee naar huis?", en: "Are you coming home with me?", te: "నాతో ఇంటికి వస్తావా?" }, cefrLevel: "A1" as const, teachingPriority: "core" as const, status: "next" as const },
  { id: "form.gaan.ovt", dutchTense: "OVT" as const, viewpoint: "past" as const, completion: "onvoltooid" as const, fullNameNl: "onvoltooid verleden tijd", sentence: "Ik ging gisteren naar het station.", naturalEnglish: "I went to the station yesterday.", usageMeaning: "past movement, routine, or story background", formula: "ik ging · wij gingen", commonUsage: "Vroeger ging ik vaak met de bus.", learnerLabelEn: "Past movement or background", canonicalExample: { nl: "Ik ging gisteren naar het station.", en: "I went to the station yesterday.", te: "నేను నిన్న స్టేషన్‌కు వెళ్లాను." }, commonUsageExample: { nl: "Vroeger ging ik vaak met de bus.", en: "I used to go by bus often.", te: "గతంలో నేను తరచుగా బస్సులో వెళ్లేవాడిని." }, cefrLevel: "A2" as const, teachingPriority: "core" as const, status: "later" as const },
  { id: "form.gaan.vtt", dutchTense: "VTT" as const, viewpoint: "present" as const, completion: "voltooid" as const, fullNameNl: "voltooid tegenwoordige tijd", sentence: "Ik ben naar huis gegaan.", naturalEnglish: "I have gone home.", usageMeaning: "completed movement viewed from the present", formula: "ik ben + … + gegaan", commonUsage: "Zij is al naar huis gegaan.", learnerLabelEn: "Completed movement from now", canonicalExample: { nl: "Ik ben naar huis gegaan.", en: "I have gone home.", te: "నేను ఇంటికి వెళ్లాను." }, commonUsageExample: { nl: "Zij is al naar huis gegaan.", en: "She has already gone home.", te: "ఆమె ఇప్పటికే ఇంటికి వెళ్లింది." }, cefrLevel: "A2" as const, teachingPriority: "core" as const, status: "later" as const },
  { id: "form.gaan.vvt", dutchTense: "VVT" as const, viewpoint: "past" as const, completion: "voltooid" as const, fullNameNl: "voltooid verleden tijd", sentence: "Ik was al naar huis gegaan.", naturalEnglish: "I had already gone home.", usageMeaning: "completed movement before another past point", formula: "ik was + … + gegaan", commonUsage: "Ik was al naar huis gegaan voordat het regende.", learnerLabelEn: "Earlier completed movement", canonicalExample: { nl: "Ik was al naar huis gegaan.", en: "I had already gone home.", te: "నేను అప్పటికే ఇంటికి వెళ్లిపోయాను." }, commonUsageExample: { nl: "Ik was al naar huis gegaan voordat het regende.", en: "I had already gone home before it rained.", te: "వర్షం పడకముందే నేను ఇంటికి వెళ్లిపోయాను." }, cefrLevel: "A2" as const, teachingPriority: "later" as const, status: "later" as const },
  { id: "form.gaan.ottt", dutchTense: "OTTT" as const, viewpoint: "future" as const, completion: "onvoltooid" as const, fullNameNl: "onvoltooid tegenwoordige toekomende tijd", sentence: "Ik zal morgen naar Utrecht gaan.", naturalEnglish: "I will go to Utrecht tomorrow.", usageMeaning: "explicit future movement or prediction", formula: "ik zal + … + gaan", commonUsage: "Morgen ga ik naar Utrecht.", learnerLabelEn: "Explicit future movement", canonicalExample: { nl: "Ik zal morgen naar Utrecht gaan.", en: "I will go to Utrecht tomorrow.", te: "నేను రేపు ఉట్రెక్ట్‌కు వెళ్తాను." }, commonUsageExample: { nl: "Morgen ga ik naar Utrecht.", en: "Tomorrow I am going to Utrecht.", te: "రేపు నేను ఉట్రెక్ట్‌కు వెళ్తాను." }, cefrLevel: "A2" as const, teachingPriority: "later" as const, status: "later" as const },
  { id: "form.gaan.ovtt", dutchTense: "OVTT" as const, viewpoint: "future-from-past" as const, completion: "onvoltooid" as const, fullNameNl: "onvoltooid verleden toekomende tijd", sentence: "Ik zou naar de markt gaan.", naturalEnglish: "I would go to the market.", usageMeaning: "conditional or hypothetical movement", formula: "ik zou + … + gaan", commonUsage: "Als ik tijd had, zou ik naar de markt gaan.", learnerLabelEn: "Conditional movement", canonicalExample: { nl: "Ik zou naar de markt gaan.", en: "I would go to the market.", te: "నేను మార్కెట్‌కు వెళ్లేవాడిని." }, commonUsageExample: { nl: "Als ik tijd had, zou ik naar de markt gaan.", en: "If I had time, I would go to the market.", te: "నాకు సమయం ఉంటే, నేను మార్కెట్‌కు వెళ్లేవాడిని." }, cefrLevel: "A2" as const, teachingPriority: "later" as const, status: "later" as const },
  { id: "form.gaan.vttt", dutchTense: "VTTT" as const, viewpoint: "future" as const, completion: "voltooid" as const, fullNameNl: "voltooid tegenwoordige toekomende tijd", sentence: "Tegen acht uur zal ik naar huis gegaan zijn.", naturalEnglish: "By eight o'clock, I will have gone home.", usageMeaning: "completed movement before a future point", formula: "ik zal + … + gegaan zijn", commonUsage: "Tegen acht uur ben ik naar huis gegaan.", learnerLabelEn: "Completed before a future point", canonicalExample: { nl: "Tegen acht uur zal ik naar huis gegaan zijn.", en: "By eight o'clock, I will have gone home.", te: "ఎనిమిది గంటలకల్లా నేను ఇంటికి వెళ్లి ఉంటాను." }, commonUsageExample: { nl: "Tegen acht uur ben ik naar huis gegaan.", en: "By eight o'clock, I have gone home.", te: "ఎనిమిది గంటలకల్లా నేను ఇంటికి వెళ్లాను." }, cefrLevel: "reference" as const, teachingPriority: "reference" as const, status: "reference" as const },
  { id: "form.gaan.vvtt", dutchTense: "VVTT" as const, viewpoint: "future-from-past" as const, completion: "voltooid" as const, fullNameNl: "voltooid verleden toekomende tijd", sentence: "Ik zou naar de markt gegaan zijn.", naturalEnglish: "I would have gone to the market.", usageMeaning: "unreal or hypothetical completed movement", formula: "ik zou + … + gegaan zijn", commonUsage: "Als ik vrij was geweest, zou ik naar de markt gegaan zijn.", learnerLabelEn: "Unreal completed movement", canonicalExample: { nl: "Ik zou naar de markt gegaan zijn.", en: "I would have gone to the market.", te: "నేను మార్కెట్‌కు వెళ్లి ఉండేవాడిని." }, commonUsageExample: { nl: "Als ik vrij was geweest, zou ik naar de markt gegaan zijn.", en: "If I had been free, I would have gone to the market.", te: "నేను ఖాళీగా ఉండి ఉంటే, మార్కెట్‌కు వెళ్లి ఉండేవాడిని." }, cefrLevel: "reference" as const, teachingPriority: "reference" as const, status: "reference" as const },
];

const gaanJourneys: JourneyRecord[] = [
  {
    id: "journey.gaan.ott-plans", verbId: "verb.gaan", title: "Plans and near future", subtitle: "OTT · gaan + infinitive and inversion", level: "A1" as const, kind: "core" as const, status: "next" as const, targetForms: ["OTT" as const], targetSkills: ["skill.gaan.ott-plans"], learningGoal: "Talk about a plan with gaan plus an infinitive and recognise inversion after a time phrase.", estimatedMinutes: 3, storyTitle: "Wat ik straks ga doen",
    story: [
      { id: "story.gaan.ott-plans.01", nl: "Ik ga vanavond koken.", english: "I am going to cook tonight.", telugu: "నేను ఈ రాత్రి వంట చేయబోతున్నాను.", targets: [{ text: "ga", skillIds: ["skill.gaan.ott-plans"] }] },
      { id: "story.gaan.ott-plans.02", nl: "Mijn vriend gaat morgen bellen.", english: "My friend is going to call tomorrow.", telugu: "నా స్నేహితుడు రేపు ఫోన్ చేయబోతున్నాడు.", targets: [{ text: "gaat", skillIds: ["skill.gaan.ott-plans"] }] },
      { id: "story.gaan.ott-plans.03", nl: "Ga je straks studeren?", english: "Are you going to study soon?", telugu: "నువ్వు కొద్దిసేపట్లో చదవబోతున్నావా?", targets: [{ text: "Ga", skillIds: ["skill.gaan.ott-plans"] }] },
      { id: "story.gaan.ott-plans.04", nl: "Morgen ga ik vroeg vertrekken.", english: "Tomorrow I am going to leave early.", telugu: "రేపు నేను త్వరగా బయలుదేరబోతున్నాను.", targets: [{ text: "ga", skillIds: ["skill.gaan.ott-plans"] }] },
      { id: "story.gaan.ott-plans.05", nl: "Wij gaan samen een film kijken.", english: "We are going to watch a film together.", telugu: "మేము కలిసి ఒక సినిమా చూడబోతున్నాము.", targets: [{ text: "gaan", skillIds: ["skill.gaan.ott-plans"] }] },
    ],
    notice: { id: "notice.gaan.ott-plans", title: "A plan with gaan", subtitle: "Gaan plus an infinitive points forward to a plan or intended action.", comparison: [
      { label: "plan", tense: "OTT", sentence: "Ik ga vanavond koken.", meaning: "a near-future plan" },
      { label: "inversion", tense: "OTT", sentence: "Morgen ga ik vroeg vertrekken.", meaning: "time first, verb before subject" },
      { label: "question", tense: "OTT", sentence: "Ga je straks studeren?", meaning: "a question about a plan" },
    ], formula: "ik ga + infinitive · morgen ga ik + infinitive", formulaNote: "Gaan carries the present form; the second verb stays in the infinitive: Ik ga koken.", valuableContrast: "Ik ga vanavond koken describes a planned action. Ik ga naar de markt describes movement; the same present forms work in both patterns." },
  },
  {
    id: "journey.gaan.ovt-movement", verbId: "verb.gaan", title: "Past movement", subtitle: "OVT · ging and gingen", level: "A2" as const, kind: "core" as const, status: "later" as const, targetForms: ["OVT" as const], targetSkills: ["skill.gaan.ovt-movement"], learningGoal: "Describe past movement or story background with ging and gingen.", estimatedMinutes: 3, storyTitle: "Gisteren onderweg",
    story: [
      { id: "story.gaan.ovt-movement.01", nl: "Gisteren ging ik naar het station.", english: "Yesterday I went to the station.", telugu: "నిన్న నేను స్టేషన్‌కు వెళ్లాను.", targets: [{ text: "ging", skillIds: ["skill.gaan.ovt-movement"] }] },
      { id: "story.gaan.ovt-movement.02", nl: "Vroeger ging zij vaak met de trein.", english: "She used to go by train often.", telugu: "గతంలో ఆమె తరచుగా రైలులో వెళ్లేది.", targets: [{ text: "ging", skillIds: ["skill.gaan.ovt-movement"] }] },
      { id: "story.gaan.ovt-movement.03", nl: "Ging jij alleen naar huis?", english: "Did you go home alone?", telugu: "నువ్వు ఒంటరిగా ఇంటికి వెళ్లావా?", targets: [{ text: "Ging", skillIds: ["skill.gaan.ovt-movement"] }] },
      { id: "story.gaan.ovt-movement.04", nl: "Hij ging door de regen naar zijn werk.", english: "He went to work through the rain.", telugu: "అతను వర్షంలో తన పనికి వెళ్లాడు.", targets: [{ text: "ging", skillIds: ["skill.gaan.ovt-movement"] }] },
      { id: "story.gaan.ovt-movement.05", nl: "Wij gingen samen naar de kust.", english: "We went to the coast together.", telugu: "మేము కలిసి సముద్రతీరానికి వెళ్లాము.", targets: [{ text: "gingen", skillIds: ["skill.gaan.ovt-movement"] }] },
    ],
    notice: { id: "notice.gaan.ovt-movement", title: "Looking back with gaan", subtitle: "Ging and gingen place movement in a past story or routine.", comparison: [
      { label: "singular", tense: "OVT", sentence: "Gisteren ging ik naar het station.", meaning: "past movement with ik" },
      { label: "plural", tense: "OVT", sentence: "Wij gingen samen naar de kust.", meaning: "past movement with wij" },
      { label: "everyday contrast", tense: "VTT", sentence: "Ik ben gisteren naar huis gegaan.", meaning: "one completed conversational fact" },
    ], formula: "ik ging · jij/hij ging · wij gingen", formulaNote: "Gaan is irregular in OVT: singular ging, plural gingen.", valuableContrast: "Ging often gives story background or a past routine. Ben gegaan is a common conversational way to report one completed movement." },
  },
  {
    id: "journey.gaan.vtt-completed-movement", verbId: "verb.gaan", title: "Completed movement", subtitle: "VTT · ben, is, zijn gegaan", level: "A2" as const, kind: "core" as const, status: "later" as const, targetForms: ["VTT" as const], targetSkills: ["skill.gaan.vtt-completed-movement"], learningGoal: "Recognise completed movement with zijn plus gegaan and keep the auxiliary matched to the subject.", estimatedMinutes: 3, storyTitle: "Al onderweg geweest",
    story: [
      { id: "story.gaan.vtt-completed-movement.01", nl: "Ik ben al naar huis gegaan.", english: "I have already gone home.", telugu: "నేను ఇప్పటికే ఇంటికి వెళ్లాను.", targets: [{ text: "ben", skillIds: ["skill.gaan.vtt-completed-movement"] }, { text: "gegaan", skillIds: ["skill.gaan.vtt-completed-movement"] }] },
      { id: "story.gaan.vtt-completed-movement.02", nl: "Zij is naar de winkel gegaan.", english: "She has gone to the shop.", telugu: "ఆమె దుకాణానికి వెళ్లింది.", targets: [{ text: "is", skillIds: ["skill.gaan.vtt-completed-movement"] }, { text: "gegaan", skillIds: ["skill.gaan.vtt-completed-movement"] }] },
      { id: "story.gaan.vtt-completed-movement.03", nl: "Ben jij al naar buiten gegaan?", english: "Have you already gone outside?", telugu: "నువ్వు ఇప్పటికే బయటకు వెళ్లావా?", targets: [{ text: "Ben", skillIds: ["skill.gaan.vtt-completed-movement"] }, { text: "gegaan", skillIds: ["skill.gaan.vtt-completed-movement"] }] },
      { id: "story.gaan.vtt-completed-movement.04", nl: "Hij is vroeg naar kantoor gegaan.", english: "He went to the office early.", telugu: "అతను ఉదయాన్నే ఆఫీసుకు వెళ్లాడు.", targets: [{ text: "is", skillIds: ["skill.gaan.vtt-completed-movement"] }, { text: "gegaan", skillIds: ["skill.gaan.vtt-completed-movement"] }] },
      { id: "story.gaan.vtt-completed-movement.05", nl: "Wij zijn samen naar het museum gegaan.", english: "We went to the museum together.", telugu: "మేము కలిసి మ్యూజియంకు వెళ్లాము.", targets: [{ text: "zijn", skillIds: ["skill.gaan.vtt-completed-movement"] }, { text: "gegaan", skillIds: ["skill.gaan.vtt-completed-movement"] }] },
    ],
    notice: { id: "notice.gaan.vtt-completed-movement", title: "Completed movement with zijn", subtitle: "The auxiliary changes with the subject; gegaan stays the same.", comparison: [
      { label: "ik", tense: "VTT", sentence: "Ik ben naar huis gegaan.", meaning: "completed movement" },
      { label: "hij/zij", tense: "VTT", sentence: "Zij is naar de winkel gegaan.", meaning: "completed movement" },
      { label: "wij", tense: "VTT", sentence: "Wij zijn naar het museum gegaan.", meaning: "completed movement" },
    ], formula: "ik ben gegaan · hij/zij is gegaan · wij zijn gegaan", formulaNote: "This bounded movement set uses zijn plus gegaan. The participle does not change for the subject.", valuableContrast: "Ben, is, and zijn match the subject. The movement result is expressed with gegaan; this journey does not claim a universal auxiliary rule for every Dutch verb." },
  },
  {
    id: "journey.gaan.future-conditional", verbId: "verb.gaan", title: "Future and conditional movement", subtitle: "OTTT · OVTT · zal gaan and zou gaan", level: "A2" as const, kind: "core" as const, status: "later" as const, targetForms: ["OTTT" as const, "OVTT" as const], targetSkills: ["skill.gaan.future-conditional"], learningGoal: "Separate an explicit future movement from a conditional or hypothetical movement.", estimatedMinutes: 3, storyTitle: "Morgen of misschien",
    story: [
      { id: "story.gaan.future-conditional.01", nl: "Morgen zal ik naar Utrecht gaan.", english: "Tomorrow I will go to Utrecht.", telugu: "రేపు నేను ఉట్రెక్ట్‌కు వెళ్తాను.", targets: [{ text: "zal", skillIds: ["skill.gaan.future-conditional"] }, { text: "gaan", skillIds: ["skill.gaan.future-conditional"] }] },
      { id: "story.gaan.future-conditional.02", nl: "Volgende week zal zij naar haar familie gaan.", english: "Next week she will go to her family.", telugu: "వచ్చే వారం ఆమె తన కుటుంబం దగ్గరకు వెళ్తుంది.", targets: [{ text: "zal", skillIds: ["skill.gaan.future-conditional"] }, { text: "gaan", skillIds: ["skill.gaan.future-conditional"] }] },
      { id: "story.gaan.future-conditional.03", nl: "Als ik tijd had, zou ik naar de markt gaan.", english: "If I had time, I would go to the market.", telugu: "నాకు సమయం ఉంటే, నేను మార్కెట్‌కు వెళ్లేవాడిని.", targets: [{ text: "zou", skillIds: ["skill.gaan.future-conditional"] }, { text: "gaan", skillIds: ["skill.gaan.future-conditional"] }] },
      { id: "story.gaan.future-conditional.04", nl: "Zou jij met ons meegaan?", english: "Would you come with us?", telugu: "నువ్వు మాతో వస్తావా?", targets: [{ text: "Zou", skillIds: ["skill.gaan.future-conditional"] }, { text: "meegaan", skillIds: ["skill.gaan.future-conditional"] }] },
      { id: "story.gaan.future-conditional.05", nl: "Morgen ga ik naar de tandarts.", english: "Tomorrow I am going to the dentist.", telugu: "రేపు నేను దంతవైద్యుడి దగ్గరకు వెళ్తాను.", targets: [{ text: "ga", skillIds: ["skill.gaan.future-conditional"] }] },
    ],
    notice: { id: "notice.gaan.future-conditional", title: "Explicit or conditional", subtitle: "Zal gaan points to an explicit future; zou gaan depends on a condition or hypothesis.", comparison: [
      { label: "future", tense: "OTTT", sentence: "Morgen zal ik naar Utrecht gaan.", meaning: "explicit future movement" },
      { label: "conditional", tense: "OVTT", sentence: "Als ik tijd had, zou ik naar de markt gaan.", meaning: "hypothetical movement" },
      { label: "everyday future", tense: "OTT", sentence: "Morgen ga ik naar de tandarts.", meaning: "future time plus OTT" },
    ], formula: "ik zal gaan · ik zou gaan", formulaNote: "Zal or zou carries the viewpoint; gaan remains the infinitive after it.", valuableContrast: "Morgen ga ik is ordinary Dutch for a planned future. Zal gaan makes the future explicit, while zou gaan makes it conditional or hypothetical." },
  },
  {
    id: "journey.gaan.reference-completed", verbId: "verb.gaan", title: "Earlier and completed-future reference", subtitle: "VVT · VTTT · VVTT", level: "A2" as const, kind: "reference" as const, status: "reference" as const, targetForms: ["VVT" as const, "VTTT" as const, "VVTT" as const], targetSkills: ["skill.gaan.reference-completed"], learningGoal: "Recognise completed movement from an earlier past, future, or hypothetical viewpoint.", estimatedMinutes: 3, storyTitle: "Een ander tijdspunt",
    story: [
      { id: "story.gaan.reference-completed.01", nl: "Ik was al naar huis gegaan voordat het begon te regenen.", english: "I had already gone home before it started raining.", telugu: "వర్షం మొదలయ్యే ముందు నేను ఇప్పటికే ఇంటికి వెళ్లిపోయాను.", targets: [{ text: "was", skillIds: ["skill.gaan.reference-completed"] }, { text: "gegaan", skillIds: ["skill.gaan.reference-completed"] }] },
      { id: "story.gaan.reference-completed.02", nl: "Tegen acht uur zal ik naar huis gegaan zijn.", english: "By eight o'clock, I will have gone home.", telugu: "ఎనిమిది గంటలకల్లా నేను ఇంటికి వెళ్లి ఉంటాను.", targets: [{ text: "zal", skillIds: ["skill.gaan.reference-completed"] }, { text: "gegaan zijn", skillIds: ["skill.gaan.reference-completed"] }] },
      { id: "story.gaan.reference-completed.03", nl: "Als ik vrij was geweest, zou ik naar de kust gegaan zijn.", english: "If I had been free, I would have gone to the coast.", telugu: "నేను ఖాళీగా ఉండి ఉంటే, సముద్రతీరానికి వెళ్లేవాడిని.", targets: [{ text: "zou", skillIds: ["skill.gaan.reference-completed"] }, { text: "gegaan zijn", skillIds: ["skill.gaan.reference-completed"] }] },
      { id: "story.gaan.reference-completed.04", nl: "Zij was al naar de winkel gegaan toen ik belde.", english: "She had already gone to the shop when I called.", telugu: "నేను ఫోన్ చేసినప్పుడు ఆమె ఇప్పటికే దుకాణానికి వెళ్లింది.", targets: [{ text: "was", skillIds: ["skill.gaan.reference-completed"] }, { text: "gegaan", skillIds: ["skill.gaan.reference-completed"] }] },
      { id: "story.gaan.reference-completed.05", nl: "Voor het einde van de dag zullen wij naar huis gegaan zijn.", english: "Before the end of the day, we will have gone home.", telugu: "రోజు ముగిసేలోపు మేము ఇంటికి వెళ్లి ఉంటాము.", targets: [{ text: "zullen", skillIds: ["skill.gaan.reference-completed"] }, { text: "gegaan zijn", skillIds: ["skill.gaan.reference-completed"] }] },
    ],
    notice: { id: "notice.gaan.reference-completed", title: "Completed from another viewpoint", subtitle: "Was gegaan, zal gegaan zijn, and zou gegaan zijn place completed movement relative to another time or condition.", comparison: [
      { label: "earlier past", tense: "VVT", sentence: "Ik was al naar huis gegaan voordat het regende.", meaning: "before another past event" },
      { label: "future completion", tense: "VTTT", sentence: "Tegen acht uur zal ik naar huis gegaan zijn.", meaning: "before a future point" },
      { label: "hypothetical completion", tense: "VVTT", sentence: "Als ik vrij was geweest, zou ik naar de kust gegaan zijn.", meaning: "an unreal completed movement" },
    ], formula: "was gegaan · zal gegaan zijn · zou gegaan zijn", formulaNote: "These are reference forms in the eight-form map. Learn their time relationship and recognise the authored chunks before producing them freely.", valuableContrast: "VVT looks back from a past point. VTTT looks forward to a completed result, while VVTT imagines a completed movement that did not happen." },
  },
];

export const gaanPack: VerbJourneyPack = {
  schemaVersion: 1,
  contentVersion: "020-2",
  verb: { id: "verb.gaan", lemma: "gaan", english: "to go", level: "A1", tags: ["irregular", "motion"], auxiliary: "zijn" },
  dutchForms: gaanForms,
  englishComparison,
  journeys: [{
    id: "journey.gaan.ott-movement", verbId: "verb.gaan", title: "Going somewhere and leaving", subtitle: "OTT · movement and departure", level: "A1", kind: "core", status: "next", targetForms: ["OTT"], targetSkills: ["skill.gaan.ott-movement"], learningGoal: "Describe where I am going and recognise the bounded present forms of gaan.", estimatedMinutes: 3, storyTitle: "Op weg vandaag",
    story: [
      { id: "story.gaan.ott-movement.01", nl: "Ik ga vandaag naar de markt.", english: "I am going to the market today.", telugu: "నేను ఈ రోజు మార్కెట్‌కు వెళ్తాను.", targets: [{ text: "ga", skillIds: ["skill.gaan.ott-movement"] }] },
      { id: "story.gaan.ott-movement.02", nl: "Jij gaat straks naar het station.", english: "You are going to the station soon.", telugu: "నువ్వు కొద్దిసేపట్లో స్టేషన్‌కు వెళ్తావు.", targets: [{ text: "gaat", skillIds: ["skill.gaan.ott-movement"] }] },
      { id: "story.gaan.ott-movement.03", nl: "Ga je na de les naar huis?", english: "Are you going home after the lesson?", telugu: "పాఠం తర్వాత నువ్వు ఇంటికి వెళ్తావా?", targets: [{ text: "Ga je", skillIds: ["skill.gaan.ott-movement"] }] },
      { id: "story.gaan.ott-movement.04", nl: "Hij gaat met de bus naar huis.", english: "He is going home by bus.", telugu: "అతను బస్సులో ఇంటికి వెళ్తాడు.", targets: [{ text: "gaat", skillIds: ["skill.gaan.ott-movement"] }] },
      { id: "story.gaan.ott-movement.05", nl: "Wij gaan samen naar het park.", english: "We are going to the park together.", telugu: "మేము కలిసి పార్క్‌కు వెళ్తాము.", targets: [{ text: "gaan", skillIds: ["skill.gaan.ott-movement"] }] },
    ],
    notice: { id: "notice.gaan.ott-movement", title: "The present forms of gaan", subtitle: "The subject changes the present form, while the movement meaning stays the same.", comparison: [
      { label: "ik", tense: "OTT", sentence: "Ik ga vandaag naar de markt.", meaning: "ga follows ik" },
      { label: "jij / hij", tense: "OTT", sentence: "Jij gaat naar het station. / Hij gaat naar huis.", meaning: "gaat follows jij or hij" },
      { label: "wij", tense: "OTT", sentence: "Wij gaan samen naar het park.", meaning: "gaan follows wij" },
      { label: "explicit future", tense: "OTTT", sentence: "Morgen zal ik naar Utrecht gaan.", meaning: "zal gaan makes the future explicit" },
    ], formula: "ik ga · jij gaat · hij/zij gaat · wij gaan", formulaNote: "Gaan is irregular. Learn these bounded present forms from the subject; this journey does not claim uncued full-paradigm production.", valuableContrast: "Ik ga naar huis describes present movement or a plan. Morgen zal ik naar Utrecht gaan makes the future explicit; everyday Dutch can also say Morgen ga ik naar Utrecht.", },
  }, ...gaanJourneys],
};
